# Base image
FROM python:3.12-slim

WORKDIR /app

COPY libagora_allosaurus_rs.so /usr/local/lib/

RUN ldconfig

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libssl-dev \
    pkg-config \
    python3-venv  # Ensure the venv module is installed

COPY agora-allosaurus-py /app/agora-allosaurus-py
COPY agora-allosaurus-rs /app/agora-allosaurus-rs
COPY witness-server-py /app/witness-server-py
COPY libagora_allosaurus_rs.so /app
COPY requirements.txt /app

RUN python3 -m venv venv \
    && . venv/bin/activate \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir -r requirements.txt

RUN apt-get remove -y build-essential curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 80
    
CMD ["/app/venv/bin/uvicorn", "witness-server-py.main:app", "--host", "0.0.0.0", "--port", "80"]

